### ISSUE TITLE
Problem about unzip  compressed  A2D_feature and JMDB_feature files

### ISSUE THREAD

**Issue by jianhua2022** [haowang1992/ACGA#1]
Hi, Hao wang,
  I am interested in your work ACGA and want to reproduce the experimental results presented on your paper, I have download the A2D extracted feature and JHMDB extracted feature from BaiduNetDisk, and follow your method to unzip the data  but failed.  It seems that tar can not open the tar file.  Could you check the compressed data and help me to unzip the data?

![comand](https://user-images.githubusercontent.com/28485169/90370059-52b16200-e09f-11ea-9862-7fcd190b4ac0.PNG)
![error](https://user-images.githubusercontent.com/28485169/90370080-57761600-e09f-11ea-977f-98bace5a42a7.PNG)

Best Regards.

**Comment by haowang1992** [comment]
Sorry about that. Have fixed the command in README.md file.
